from docx import Document
from docx.shared import Pt, Cm
from docx.oxml.ns import qn
d=Document(); s=d.styles['Normal']; s.font.name='Times New Roman'; s.font.size=Pt(11)
for m in ('left_margin','right_margin'): setattr(d.sections[0],m,Cm(2.3))
h=d.add_paragraph(); r=h.add_run('Temperature Paper A: response to Daniel Scott\'s comments'); r.bold=True; r.font.size=Pt(14)
d.add_paragraph('The paper has been rebuilt around one question: is the rapid night-time warming in the UAE\'s fast-growing cities an urban signal that the regional climate datasets and projections used for planning do not contain? '
 'The shade-WBGT screening, hot–dry SPEI co-occurrence, population-exposure decomposition and exploratory index have been removed; they belong to the separate exposure paper. All periods and reference baselines now follow established conventions: a 30-year trend period (1995–2024), the 1991–2020 WMO climatological normal for anomalies and percentile thresholds, ETCCDI definitions for the warm-night indices, IPCC AR6 baselines and time slices for the projections, and the UN Degree of Urbanisation for the urban/rural classification. '
 'Trends are Theil–Sen with Mann–Kendall (Hamed–Rao) testing and false-discovery-rate control on the maps. Three new analyses were added: seven HadISD stations instead of three airports, a 1996–2024 satellite land-surface temperature analysis against GHS built-up growth with distance from the coast controlled, and station-level and 0.25° comparisons with ERA5-Land and 28 NEX-GDDP-CMIP6 models.')
C=[
("C0 – Which journal?","The revised paper is a focused urban-climate study with a planning implication. Best fits: Urban Climate (Elsevier) as the natural home; Communications Earth & Environment or Geophysical Research Letters if a shorter, higher-profile letter version is preferred; International Journal of Climatology as a safe alternative. The text is currently journal-agnostic (about 6,300 words of main text, 7 figures, 6 tables and 2 supplementary tables)."),
("C1 – Is the objective product intercomparison or heat exposure?","Neither, as separate aims. The single objective is to test whether urban growth explains the rapid night-time warming and whether planning products contain it (Introduction, final paragraph). Product comparison is now a means to that end, and the exposure material has been removed."),
("C2 – How many stations?","Eight UAE HadISD stations were examined; six meet the completeness rule for 1996–2024 (Dubai, Sharjah, Abu Dhabi, Al Ain, Ras Al Khaimah, Fujairah) and seven for 1991–2020 (adding Al Bateen). Section 2.2 and Table 2."),
("C3 – Why shade WBGT?","Removed. It answered a different question (heat stress) and is better placed in the exposure paper."),
("C4 – Why population data?","Removed for the same reason. Population is not needed to answer the new question."),
("C5 – Why Tmax/Tmin?","Because urban effects in hot deserts are opposite by day and night: urban surfaces warm nights and cool days relative to open desert. Separating Tmin from Tmax is what reveals the urban signal (Sections 3.2–3.3, 4.1)."),
("C6 – 'Station': what does that mean?","Defined in Section 2.2 as HadISD quality-controlled synoptic stations, all located at airports, with names and processing rules given."),
("C7 – Country scale vs airports; inland warming and urban heat island vs coastal moderation","Addressed directly. Coastal distance and urban growth are separated at the station level (Fujairah is closest to the sea but has no urban growth; Sharjah has the most) and at the pixel level by matching urban and rural pixels within coastal-distance bands. The missing warming scales with urban growth (ρ = 0.89) and not with coastal distance (ρ = −0.03). Inland Al Ain shows intermediate warming (0.60 °C/decade). Country-scale products are compared with rural pixels, which they reproduce well (Section 3.3). Coastal humidity was also tested directly with station dewpoint: dewpoint trends are small and unrelated to urban growth, and removing them leaves the Tmin trends essentially unchanged (Section 3.5, Fig. 7d)."),
("C8 – 'Massive urban growth over this period = major change in urban heat island. That change would be noteworthy if documented well.'","This is now the core of the paper. UAE built-up surface doubled from 298 to 618 km² (1995–2020). Night-time surface warming rises by 0.49 °C/decade per 10 pp of added built-up surface, and the urban-minus-rural night difference grew by 0.90 °C/decade in step with built-up growth, consistently across satellite-sensor eras (Figs 3–5). The signal is not a greening effect (land that greened without being built on shows no night-time excess), and satellite-measured albedo darkening and night-light emission account for about 60% of it, is strongest in summer, and has made summer hot nights at the city stations increase three to five times faster than ERA5-Land indicates (Section 3.5, Fig. 7)."),
("C9 – Unclear 'bias' sentence","Removed. The paper now distinguishes explicitly between the regional background, which the products represent well, and the urban increment, which they lack (Sections 3.3, 3.5, 4.2)."),
("C10 – 7.8 days on what baseline?","This belonged to the WBGT analysis, which has been removed."),
("C11 – Exposure could be the focal question","Agreed that it could be the focus of a paper; it is now the separate exposure paper, so this paper keeps a single temperature and urban focus."),
("C12 – Future not framed","Future change is now framed around the planning question. NEX-GDDP-CMIP6 projects UAE-area Tmin warming of 1.8 °C (SSP2-4.5) and 2.5 °C (SSP5-8.5) by 2041–2060. The urban warming already missing from ERA5-Land at Dubai (2.9 °C since 1996) is as large as or larger than this, so projections without an urban increment understate city night-time heat (Section 3.6, Fig. 6)."),
("C13 – 'Is this a study about temperature change and differential impacts of urban growth and heat island, or population heat exposure? Until you decide … I cannot see any journal publishing this.'","Decided: this paper is about temperature change and the differential impact of urban growth and the heat island, and about the fact that the products used for planning miss it. The population-exposure material now sits only in the separate paper."),
]
for t,a in C:
    p=d.add_paragraph(); r=p.add_run(t); r.bold=True
    d.add_paragraph(a)
d.save('Response_to_DS_comments_TempPaperA.docx')
